import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ptBR } from "@clerk/localizations"; // 👈 importa o idioma
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VitalZon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={ptBR} dynamic> {/* 👈 define o idioma aqui */}
      <html lang="pt-BR"> {/* 👈 muda o lang também */}
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <main>
            <Header />
            {children}
          </main>
          <Footer />
          <WhatsAppButton />
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
